Write headers in country csv
openstreetmap/tilelog pull request #12
Opened 2023-09-07 20:31 UTC by grischard

2023-09-07 20:55 UTC, pnorman requested changes
What's the plan for existing files, if any, as this means we'll have published files with two formats

2023-09-07 20:55 UTC, pnorman commented on tilelog/country.py
> +    csvwriter.writerow(["country", "ips", "tps", "tps_miss"])
Is there any reason [writeheader](https://docs.python.org/3/library/csv.html#csv.DictWriter.writeheader) won't work?

2023-09-07 21:32 UTC, grischard commented
Good point about existing files! We can add the header and append the existing content, then use sponge from moreutils to overwrite the original file

```bash
sudo apt install moreutils
for filename in country-*.csv; do
  { echo "country,ips,tps,tps_miss"; cat "$filename"; } | sponge "$filename"
done

I don't have access to that server, though.

2023-09-08 14:32 UTC, grischard commented
@pnorman I've added headers to the other files.

2023-09-11 08:40 UTC, pnorman requested changes
Looks good as per discussion, but I need to test and there's a couple of whitespace changes

2023-09-11 08:40 UTC, pnorman commented on tilelog/host.py
> +
Stray whitespace insertion

2023-09-11 08:40 UTC, pnorman commented on tilelog/country.py
> +
Stray whitespace that's not present in the other changes

2023-09-14 01:22 UTC, pnorman approved these changes

2023-09-14 01:51 UTC, merged